2025-03-11 20:56:09,008 ERROR: Error checking replies for account 19: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 20:56:09,012 INFO: Checking replies for account: fixyourwebsite@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 20:56:09,014 ERROR: Error checking replies for account 20: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 21:00:43,199 INFO: Email Automation System startup [in D:\W\email_automation\app\__init__.py:62]
2025-03-11 21:00:43,215 INFO: Database tables created [in D:\W\email_automation\app\__init__.py:70]
2025-03-11 21:00:43,216 INFO: Refreshing SQLAlchemy metadata to reflect current database schema [in D:\W\email_automation\app\__init__.py:75]
2025-03-11 21:00:43,217 INFO: SQLAlchemy metadata refreshed [in D:\W\email_automation\app\__init__.py:77]
2025-03-11 21:00:43,217 INFO: Initializing SocketIO for real-time updates [in D:\W\email_automation\app\__init__.py:97]
2025-03-11 21:00:43,445 INFO: Email Automation System startup [in D:\W\email_automation\app.py:27]
2025-03-11 21:00:43,446 INFO: Database tables created/verified [in D:\W\email_automation\app.py:32]
2025-03-11 21:00:43,448 INFO: Starting Email Automation Server... [in D:\W\email_automation\app.py:36]
2025-03-11 21:00:43,450 INFO: Initializing email processing scheduler... [in D:\W\email_automation\app.py:39]
2025-03-11 21:00:43,460 ERROR: Error processing email queue: (sqlite3.OperationalError) no such column: email.campaign_id
[SQL: SELECT email.id AS email_id, email.account_id AS email_account_id, email.recipient_id AS email_recipient_id, email.template_id AS email_template_id, email.campaign_id AS email_campaign_id, email.subject AS email_subject, email.body AS email_body, email.status AS email_status, email.scheduled_at AS email_scheduled_at, email.sent_at AS email_sent_at, email.response_received_at AS email_response_received_at, email.response_subject AS email_response_subject, email.response_content AS email_response_content, email.is_follow_up AS email_is_follow_up, email.parent_email_id AS email_parent_email_id, email.created_at AS email_created_at, email.updated_at AS email_updated_at 
FROM email 
WHERE email.status = ? AND email.scheduled_at <= ? ORDER BY email.scheduled_at]
[parameters: ('PENDING', '2025-03-11 21:00:43.452206')]
(Background on this error at: https://sqlalche.me/e/14/e3q8) [in D:\W\email_automation\app\utils\scheduler_utils.py:141]
2025-03-11 21:00:43,468 INFO: Starting check for email replies across all accounts [in D:\W\email_automation\app\utils\scheduler_utils.py:52]
2025-03-11 21:00:43,472 INFO: Checking 19 accounts for email replies [in D:\W\email_automation\app\utils\scheduler_utils.py:59]
2025-03-11 21:00:43,474 INFO: Checking replies for account: business@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 21:00:43,477 INFO: Connecting to IMAP server imap.hostinger.com:993 for account business@beakonagency.com [in D:\W\email_automation\app\utils\email_utils.py:414]
2025-03-11 21:00:44,123 INFO: Attempting login with username: business@beakonagency.com [in D:\W\email_automation\app\utils\email_utils.py:424]
2025-03-11 21:00:44,340 INFO: Successfully logged into IMAP server for business@beakonagency.com [in D:\W\email_automation\app\utils\email_utils.py:433]
2025-03-11 21:00:44,485 INFO: Selected INBOX with 24 messages [in D:\W\email_automation\app\utils\email_utils.py:446]
2025-03-11 21:00:44,770 ERROR: Error checking for replies: type object 'datetime.datetime' has no attribute 'datetime' [in D:\W\email_automation\app\utils\email_utils.py:621]
2025-03-11 21:00:44,773 ERROR: Traceback (most recent call last):
  File "D:\W\email_automation\app\utils\email_utils.py", line 449, in check_for_replies
    date = (datetime.datetime.now() - datetime.timedelta(days=30)).strftime("%d-%b-%Y")
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
 [in D:\W\email_automation\app\utils\email_utils.py:622]
2025-03-11 21:00:44,775 INFO: Checking replies for account: varshith@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 21:00:44,779 INFO: Connecting to IMAP server imap.hostinger.com:993 for account varshith@beakonagency.com [in D:\W\email_automation\app\utils\email_utils.py:414]
2025-03-11 21:00:45,345 INFO: Attempting login with username: varshith@beakonagency.com [in D:\W\email_automation\app\utils\email_utils.py:424]
2025-03-11 21:00:45,569 INFO: Successfully logged into IMAP server for varshith@beakonagency.com [in D:\W\email_automation\app\utils\email_utils.py:433]
2025-03-11 21:00:45,719 INFO: Selected INBOX with 1 messages [in D:\W\email_automation\app\utils\email_utils.py:446]
2025-03-11 21:00:46,008 ERROR: Error checking for replies: type object 'datetime.datetime' has no attribute 'datetime' [in D:\W\email_automation\app\utils\email_utils.py:621]
2025-03-11 21:00:46,011 ERROR: Traceback (most recent call last):
  File "D:\W\email_automation\app\utils\email_utils.py", line 449, in check_for_replies
    date = (datetime.datetime.now() - datetime.timedelta(days=30)).strftime("%d-%b-%Y")
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
 [in D:\W\email_automation\app\utils\email_utils.py:622]
2025-03-11 21:00:46,014 INFO: Checking replies for account: ridhit@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 21:00:46,016 ERROR: Error checking replies for account 3: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 21:00:46,018 INFO: Checking replies for account: alex@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 21:00:46,020 ERROR: Error checking replies for account 4: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 21:00:46,022 INFO: Checking replies for account: ethan@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 21:00:46,024 ERROR: Error checking replies for account 5: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 21:00:46,026 INFO: Checking replies for account: nova@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 21:00:46,028 ERROR: Error checking replies for account 6: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 21:00:46,030 INFO: Checking replies for account: growth@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 21:00:46,031 ERROR: Error checking replies for account 7: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 21:00:46,033 INFO: Checking replies for account: opportunities@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 21:00:46,035 ERROR: Error checking replies for account 8: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 21:00:46,038 INFO: Checking replies for account: connect@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 21:00:46,040 ERROR: Error checking replies for account 9: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 21:00:46,041 INFO: Checking replies for account: james@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 21:00:46,042 ERROR: Error checking replies for account 10: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 21:00:46,044 INFO: Checking replies for account: michael@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 21:00:46,046 ERROR: Error checking replies for account 11: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 21:00:46,048 INFO: Checking replies for account: sarah@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 21:00:46,051 ERROR: Error checking replies for account 12: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 21:00:46,053 INFO: Checking replies for account: david@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 21:00:46,055 ERROR: Error checking replies for account 13: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 21:00:46,057 INFO: Checking replies for account: emily@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 21:00:46,059 ERROR: Error checking replies for account 14: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 21:00:46,061 INFO: Checking replies for account: atlas@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 21:00:46,063 ERROR: Error checking replies for account 15: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 21:00:46,065 INFO: Checking replies for account: zion@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 21:00:46,067 ERROR: Error checking replies for account 16: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 21:00:46,069 INFO: Checking replies for account: upgrade@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
